<?php

namespace Stuzzo\Monolog\Processor;

use Monolog\Processor\WebProcessor;
use Symfony\Component\HttpFoundation\Request;

/**
 * Add Request data to the record generated by logger
 *
 * @author Alfredo Aiello <stuzzo@gmail.com>
 */
class ExtendedWebProcessor extends WebProcessor
{
    
    public function __construct($serverData = null, $extraFields = null)
    {
        parent::__construct($serverData, $extraFields);
        $this->extraFields = array_merge($this->extraFields, [
            'protocol' => 'REQUEST_SCHEME',
            'server'   => 'SERVER_ADDR',
        ]);
    }
    
    public function __invoke(array $record)
    {
        $record = parent::__invoke($record);
        
        return $record;
    }
    
}
